/// Flutter icons ApiVideoIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ApiVideoIcons
///      fonts:
///       - asset: fonts/ApiVideoIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ApiVideoIcons {
  ApiVideoIcons._();

  static const _kFontFam = 'ApiVideoIcons';
  static const String? _kFontPkg = 'apivideo_player';

  static const IconData pause_primary =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_primary =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay_primary =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
